import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/assets/css/globals.css'
import type { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-5">
          <div className="flex items-center justify-between">
            <h1 className="text-[1.5rem]">Mathilde Petit R.</h1>
            <nav className="flex items-center justify-between gap-20">
              <ul className="flex gap-20">
                <li><a href="/">Accueil</a></li>
                <li><a href="/about">A propos</a></li>
                <li><a href="/contact">Contact</a></li>
              </ul>
              <div className="button-group">
                <button>ENG</button>
                <button className="active">FRA</button>
                <button>BZH</button>
              </div>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
